/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.document.notification.system.kafka.document.avro.model;

@org.apache.avro.specific.AvroGenerated
public enum DocumentStatus implements org.apache.avro.generic.GenericEnumSymbol<DocumentStatus> {
    PENDING, GENERATED, SENT, CANCELLING, CANCELLED;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DocumentStatus\",\"namespace\":\"com.document.notification.system.kafka.document.avro.model\",\"symbols\":[\"PENDING\",\"GENERATED\",\"SENT\",\"CANCELLING\",\"CANCELLED\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
