/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.document.notification.system.kafka.document.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Event published when a document has been generated */
@org.apache.avro.specific.AvroGenerated
public class DocumentGeneratedEventAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3456981947345786956L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocumentGeneratedEventAvroModel\",\"namespace\":\"com.document.notification.system.kafka.document.avro.model\",\"doc\":\"Event published when a document has been generated\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"doc\":\"Unique identifier for the document\"},{\"name\":\"customerId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"doc\":\"Customer identifier\"},{\"name\":\"accountId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"doc\":\"Account identifier\"},{\"name\":\"fileName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Name of the generated document file\"},{\"name\":\"filePath\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Path where the document is stored\"},{\"name\":\"documentType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Type of document (PDF, CSV, XML)\"},{\"name\":\"documentStatus\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Current status of the document (should be GENERATED)\"},{\"name\":\"totalAmount\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":10,\"scale\":2},\"doc\":\"Total amount of the document\"},{\"name\":\"generatedAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Timestamp when the document was generated\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<DocumentGeneratedEventAvroModel> ENCODER =
      new BinaryMessageEncoder<DocumentGeneratedEventAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DocumentGeneratedEventAvroModel> DECODER =
      new BinaryMessageDecoder<DocumentGeneratedEventAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DocumentGeneratedEventAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DocumentGeneratedEventAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DocumentGeneratedEventAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DocumentGeneratedEventAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DocumentGeneratedEventAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DocumentGeneratedEventAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DocumentGeneratedEventAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DocumentGeneratedEventAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier for the document */
  private java.lang.String id;
  /** Customer identifier */
  private java.lang.String customerId;
  /** Account identifier */
  private java.lang.String accountId;
  /** Name of the generated document file */
  private java.lang.String fileName;
  /** Path where the document is stored */
  private java.lang.String filePath;
  /** Type of document (PDF, CSV, XML) */
  private java.lang.String documentType;
  /** Current status of the document (should be GENERATED) */
  private java.lang.String documentStatus;
  /** Total amount of the document */
  private java.math.BigDecimal totalAmount;
  /** Timestamp when the document was generated */
  private java.time.Instant generatedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DocumentGeneratedEventAvroModel() {}

  /**
   * All-args constructor.
   * @param id Unique identifier for the document
   * @param customerId Customer identifier
   * @param accountId Account identifier
   * @param fileName Name of the generated document file
   * @param filePath Path where the document is stored
   * @param documentType Type of document (PDF, CSV, XML)
   * @param documentStatus Current status of the document (should be GENERATED)
   * @param totalAmount Total amount of the document
   * @param generatedAt Timestamp when the document was generated
   */
  public DocumentGeneratedEventAvroModel(java.lang.String id, java.lang.String customerId, java.lang.String accountId, java.lang.String fileName, java.lang.String filePath, java.lang.String documentType, java.lang.String documentStatus, java.math.BigDecimal totalAmount, java.time.Instant generatedAt) {
    this.id = id;
    this.customerId = customerId;
    this.accountId = accountId;
    this.fileName = fileName;
    this.filePath = filePath;
    this.documentType = documentType;
    this.documentStatus = documentStatus;
    this.totalAmount = totalAmount;
    this.generatedAt = generatedAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return customerId;
    case 2: return accountId;
    case 3: return fileName;
    case 4: return filePath;
    case 5: return documentType;
    case 6: return documentStatus;
    case 7: return totalAmount;
    case 8: return generatedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: customerId = value$ != null ? value$.toString() : null; break;
    case 2: accountId = value$ != null ? value$.toString() : null; break;
    case 3: fileName = value$ != null ? value$.toString() : null; break;
    case 4: filePath = value$ != null ? value$.toString() : null; break;
    case 5: documentType = value$ != null ? value$.toString() : null; break;
    case 6: documentStatus = value$ != null ? value$.toString() : null; break;
    case 7: totalAmount = (java.math.BigDecimal)value$; break;
    case 8: generatedAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Unique identifier for the document
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * Unique identifier for the document
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return Customer identifier
   */
  public java.lang.String getCustomerId() {
    return customerId;
  }


  /**
   * Sets the value of the 'customerId' field.
   * Customer identifier
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.String value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'accountId' field.
   * @return Account identifier
   */
  public java.lang.String getAccountId() {
    return accountId;
  }


  /**
   * Sets the value of the 'accountId' field.
   * Account identifier
   * @param value the value to set.
   */
  public void setAccountId(java.lang.String value) {
    this.accountId = value;
  }

  /**
   * Gets the value of the 'fileName' field.
   * @return Name of the generated document file
   */
  public java.lang.String getFileName() {
    return fileName;
  }


  /**
   * Sets the value of the 'fileName' field.
   * Name of the generated document file
   * @param value the value to set.
   */
  public void setFileName(java.lang.String value) {
    this.fileName = value;
  }

  /**
   * Gets the value of the 'filePath' field.
   * @return Path where the document is stored
   */
  public java.lang.String getFilePath() {
    return filePath;
  }


  /**
   * Sets the value of the 'filePath' field.
   * Path where the document is stored
   * @param value the value to set.
   */
  public void setFilePath(java.lang.String value) {
    this.filePath = value;
  }

  /**
   * Gets the value of the 'documentType' field.
   * @return Type of document (PDF, CSV, XML)
   */
  public java.lang.String getDocumentType() {
    return documentType;
  }


  /**
   * Sets the value of the 'documentType' field.
   * Type of document (PDF, CSV, XML)
   * @param value the value to set.
   */
  public void setDocumentType(java.lang.String value) {
    this.documentType = value;
  }

  /**
   * Gets the value of the 'documentStatus' field.
   * @return Current status of the document (should be GENERATED)
   */
  public java.lang.String getDocumentStatus() {
    return documentStatus;
  }


  /**
   * Sets the value of the 'documentStatus' field.
   * Current status of the document (should be GENERATED)
   * @param value the value to set.
   */
  public void setDocumentStatus(java.lang.String value) {
    this.documentStatus = value;
  }

  /**
   * Gets the value of the 'totalAmount' field.
   * @return Total amount of the document
   */
  public java.math.BigDecimal getTotalAmount() {
    return totalAmount;
  }


  /**
   * Sets the value of the 'totalAmount' field.
   * Total amount of the document
   * @param value the value to set.
   */
  public void setTotalAmount(java.math.BigDecimal value) {
    this.totalAmount = value;
  }

  /**
   * Gets the value of the 'generatedAt' field.
   * @return Timestamp when the document was generated
   */
  public java.time.Instant getGeneratedAt() {
    return generatedAt;
  }


  /**
   * Sets the value of the 'generatedAt' field.
   * Timestamp when the document was generated
   * @param value the value to set.
   */
  public void setGeneratedAt(java.time.Instant value) {
    this.generatedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new DocumentGeneratedEventAvroModel RecordBuilder.
   * @return A new DocumentGeneratedEventAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder newBuilder() {
    return new com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder();
  }

  /**
   * Creates a new DocumentGeneratedEventAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DocumentGeneratedEventAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder newBuilder(com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder other) {
    if (other == null) {
      return new com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder();
    } else {
      return new com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new DocumentGeneratedEventAvroModel RecordBuilder by copying an existing DocumentGeneratedEventAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new DocumentGeneratedEventAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder newBuilder(com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel other) {
    if (other == null) {
      return new com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder();
    } else {
      return new com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for DocumentGeneratedEventAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocumentGeneratedEventAvroModel>
    implements org.apache.avro.data.RecordBuilder<DocumentGeneratedEventAvroModel> {

    /** Unique identifier for the document */
    private java.lang.String id;
    /** Customer identifier */
    private java.lang.String customerId;
    /** Account identifier */
    private java.lang.String accountId;
    /** Name of the generated document file */
    private java.lang.String fileName;
    /** Path where the document is stored */
    private java.lang.String filePath;
    /** Type of document (PDF, CSV, XML) */
    private java.lang.String documentType;
    /** Current status of the document (should be GENERATED) */
    private java.lang.String documentStatus;
    /** Total amount of the document */
    private java.math.BigDecimal totalAmount;
    /** Timestamp when the document was generated */
    private java.time.Instant generatedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.accountId)) {
        this.accountId = data().deepCopy(fields()[2].schema(), other.accountId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.fileName)) {
        this.fileName = data().deepCopy(fields()[3].schema(), other.fileName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.filePath)) {
        this.filePath = data().deepCopy(fields()[4].schema(), other.filePath);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.documentType)) {
        this.documentType = data().deepCopy(fields()[5].schema(), other.documentType);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.documentStatus)) {
        this.documentStatus = data().deepCopy(fields()[6].schema(), other.documentStatus);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[7].schema(), other.totalAmount);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.generatedAt)) {
        this.generatedAt = data().deepCopy(fields()[8].schema(), other.generatedAt);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
    }

    /**
     * Creates a Builder by copying an existing DocumentGeneratedEventAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.accountId)) {
        this.accountId = data().deepCopy(fields()[2].schema(), other.accountId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.fileName)) {
        this.fileName = data().deepCopy(fields()[3].schema(), other.fileName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.filePath)) {
        this.filePath = data().deepCopy(fields()[4].schema(), other.filePath);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.documentType)) {
        this.documentType = data().deepCopy(fields()[5].schema(), other.documentType);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.documentStatus)) {
        this.documentStatus = data().deepCopy(fields()[6].schema(), other.documentStatus);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.totalAmount)) {
        this.totalAmount = data().deepCopy(fields()[7].schema(), other.totalAmount);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.generatedAt)) {
        this.generatedAt = data().deepCopy(fields()[8].schema(), other.generatedAt);
        fieldSetFlags()[8] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * Unique identifier for the document
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * Unique identifier for the document
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Unique identifier for the document
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Unique identifier for the document
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerId' field.
      * Customer identifier
      * @return The value.
      */
    public java.lang.String getCustomerId() {
      return customerId;
    }


    /**
      * Sets the value of the 'customerId' field.
      * Customer identifier
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder setCustomerId(java.lang.String value) {
      validate(fields()[1], value);
      this.customerId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * Customer identifier
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerId' field.
      * Customer identifier
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder clearCustomerId() {
      customerId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountId' field.
      * Account identifier
      * @return The value.
      */
    public java.lang.String getAccountId() {
      return accountId;
    }


    /**
      * Sets the value of the 'accountId' field.
      * Account identifier
      * @param value The value of 'accountId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder setAccountId(java.lang.String value) {
      validate(fields()[2], value);
      this.accountId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'accountId' field has been set.
      * Account identifier
      * @return True if the 'accountId' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'accountId' field.
      * Account identifier
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder clearAccountId() {
      accountId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'fileName' field.
      * Name of the generated document file
      * @return The value.
      */
    public java.lang.String getFileName() {
      return fileName;
    }


    /**
      * Sets the value of the 'fileName' field.
      * Name of the generated document file
      * @param value The value of 'fileName'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder setFileName(java.lang.String value) {
      validate(fields()[3], value);
      this.fileName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'fileName' field has been set.
      * Name of the generated document file
      * @return True if the 'fileName' field has been set, false otherwise.
      */
    public boolean hasFileName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'fileName' field.
      * Name of the generated document file
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder clearFileName() {
      fileName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'filePath' field.
      * Path where the document is stored
      * @return The value.
      */
    public java.lang.String getFilePath() {
      return filePath;
    }


    /**
      * Sets the value of the 'filePath' field.
      * Path where the document is stored
      * @param value The value of 'filePath'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder setFilePath(java.lang.String value) {
      validate(fields()[4], value);
      this.filePath = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'filePath' field has been set.
      * Path where the document is stored
      * @return True if the 'filePath' field has been set, false otherwise.
      */
    public boolean hasFilePath() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'filePath' field.
      * Path where the document is stored
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder clearFilePath() {
      filePath = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentType' field.
      * Type of document (PDF, CSV, XML)
      * @return The value.
      */
    public java.lang.String getDocumentType() {
      return documentType;
    }


    /**
      * Sets the value of the 'documentType' field.
      * Type of document (PDF, CSV, XML)
      * @param value The value of 'documentType'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder setDocumentType(java.lang.String value) {
      validate(fields()[5], value);
      this.documentType = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'documentType' field has been set.
      * Type of document (PDF, CSV, XML)
      * @return True if the 'documentType' field has been set, false otherwise.
      */
    public boolean hasDocumentType() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'documentType' field.
      * Type of document (PDF, CSV, XML)
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder clearDocumentType() {
      documentType = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentStatus' field.
      * Current status of the document (should be GENERATED)
      * @return The value.
      */
    public java.lang.String getDocumentStatus() {
      return documentStatus;
    }


    /**
      * Sets the value of the 'documentStatus' field.
      * Current status of the document (should be GENERATED)
      * @param value The value of 'documentStatus'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder setDocumentStatus(java.lang.String value) {
      validate(fields()[6], value);
      this.documentStatus = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'documentStatus' field has been set.
      * Current status of the document (should be GENERATED)
      * @return True if the 'documentStatus' field has been set, false otherwise.
      */
    public boolean hasDocumentStatus() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'documentStatus' field.
      * Current status of the document (should be GENERATED)
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder clearDocumentStatus() {
      documentStatus = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'totalAmount' field.
      * Total amount of the document
      * @return The value.
      */
    public java.math.BigDecimal getTotalAmount() {
      return totalAmount;
    }


    /**
      * Sets the value of the 'totalAmount' field.
      * Total amount of the document
      * @param value The value of 'totalAmount'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder setTotalAmount(java.math.BigDecimal value) {
      validate(fields()[7], value);
      this.totalAmount = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'totalAmount' field has been set.
      * Total amount of the document
      * @return True if the 'totalAmount' field has been set, false otherwise.
      */
    public boolean hasTotalAmount() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'totalAmount' field.
      * Total amount of the document
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder clearTotalAmount() {
      totalAmount = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'generatedAt' field.
      * Timestamp when the document was generated
      * @return The value.
      */
    public java.time.Instant getGeneratedAt() {
      return generatedAt;
    }


    /**
      * Sets the value of the 'generatedAt' field.
      * Timestamp when the document was generated
      * @param value The value of 'generatedAt'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder setGeneratedAt(java.time.Instant value) {
      validate(fields()[8], value);
      this.generatedAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'generatedAt' field has been set.
      * Timestamp when the document was generated
      * @return True if the 'generatedAt' field has been set, false otherwise.
      */
    public boolean hasGeneratedAt() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'generatedAt' field.
      * Timestamp when the document was generated
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGeneratedEventAvroModel.Builder clearGeneratedAt() {
      fieldSetFlags()[8] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DocumentGeneratedEventAvroModel build() {
      try {
        DocumentGeneratedEventAvroModel record = new DocumentGeneratedEventAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.customerId = fieldSetFlags()[1] ? this.customerId : (java.lang.String) defaultValue(fields()[1]);
        record.accountId = fieldSetFlags()[2] ? this.accountId : (java.lang.String) defaultValue(fields()[2]);
        record.fileName = fieldSetFlags()[3] ? this.fileName : (java.lang.String) defaultValue(fields()[3]);
        record.filePath = fieldSetFlags()[4] ? this.filePath : (java.lang.String) defaultValue(fields()[4]);
        record.documentType = fieldSetFlags()[5] ? this.documentType : (java.lang.String) defaultValue(fields()[5]);
        record.documentStatus = fieldSetFlags()[6] ? this.documentStatus : (java.lang.String) defaultValue(fields()[6]);
        record.totalAmount = fieldSetFlags()[7] ? this.totalAmount : (java.math.BigDecimal) defaultValue(fields()[7]);
        record.generatedAt = fieldSetFlags()[8] ? this.generatedAt : (java.time.Instant) defaultValue(fields()[8]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DocumentGeneratedEventAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<DocumentGeneratedEventAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DocumentGeneratedEventAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<DocumentGeneratedEventAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










