/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.document.notification.system.kafka.document.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Event published when a document has been cancelled */
@org.apache.avro.specific.AvroGenerated
public class DocumentCancelledEventAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -517074112409569531L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocumentCancelledEventAvroModel\",\"namespace\":\"com.document.notification.system.kafka.document.avro.model\",\"doc\":\"Event published when a document has been cancelled\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"doc\":\"Unique identifier for the document\"},{\"name\":\"customerId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"doc\":\"Customer identifier\"},{\"name\":\"accountId\",\"type\":[\"null\",{\"type\":\"string\",\"logicalType\":\"uuid\"}],\"doc\":\"Account identifier\",\"default\":null},{\"name\":\"documentStatus\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Current status of the document (should be CANCELLED)\"},{\"name\":\"failureMessages\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"doc\":\"List of failure/cancellation reasons\"},{\"name\":\"cancelledAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Timestamp when the document was cancelled\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<DocumentCancelledEventAvroModel> ENCODER =
      new BinaryMessageEncoder<DocumentCancelledEventAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DocumentCancelledEventAvroModel> DECODER =
      new BinaryMessageDecoder<DocumentCancelledEventAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DocumentCancelledEventAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DocumentCancelledEventAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DocumentCancelledEventAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DocumentCancelledEventAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DocumentCancelledEventAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DocumentCancelledEventAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DocumentCancelledEventAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DocumentCancelledEventAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier for the document */
  private java.lang.String id;
  /** Customer identifier */
  private java.lang.String customerId;
  /** Account identifier */
  private java.lang.String accountId;
  /** Current status of the document (should be CANCELLED) */
  private java.lang.String documentStatus;
  /** List of failure/cancellation reasons */
  private java.util.List<java.lang.String> failureMessages;
  /** Timestamp when the document was cancelled */
  private java.time.Instant cancelledAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DocumentCancelledEventAvroModel() {}

  /**
   * All-args constructor.
   * @param id Unique identifier for the document
   * @param customerId Customer identifier
   * @param accountId Account identifier
   * @param documentStatus Current status of the document (should be CANCELLED)
   * @param failureMessages List of failure/cancellation reasons
   * @param cancelledAt Timestamp when the document was cancelled
   */
  public DocumentCancelledEventAvroModel(java.lang.String id, java.lang.String customerId, java.lang.String accountId, java.lang.String documentStatus, java.util.List<java.lang.String> failureMessages, java.time.Instant cancelledAt) {
    this.id = id;
    this.customerId = customerId;
    this.accountId = accountId;
    this.documentStatus = documentStatus;
    this.failureMessages = failureMessages;
    this.cancelledAt = cancelledAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return customerId;
    case 2: return accountId;
    case 3: return documentStatus;
    case 4: return failureMessages;
    case 5: return cancelledAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: customerId = value$ != null ? value$.toString() : null; break;
    case 2: accountId = value$ != null ? value$.toString() : null; break;
    case 3: documentStatus = value$ != null ? value$.toString() : null; break;
    case 4: failureMessages = (java.util.List<java.lang.String>)value$; break;
    case 5: cancelledAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Unique identifier for the document
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * Unique identifier for the document
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return Customer identifier
   */
  public java.lang.String getCustomerId() {
    return customerId;
  }


  /**
   * Sets the value of the 'customerId' field.
   * Customer identifier
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.String value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'accountId' field.
   * @return Account identifier
   */
  public java.lang.String getAccountId() {
    return accountId;
  }


  /**
   * Sets the value of the 'accountId' field.
   * Account identifier
   * @param value the value to set.
   */
  public void setAccountId(java.lang.String value) {
    this.accountId = value;
  }

  /**
   * Gets the value of the 'documentStatus' field.
   * @return Current status of the document (should be CANCELLED)
   */
  public java.lang.String getDocumentStatus() {
    return documentStatus;
  }


  /**
   * Sets the value of the 'documentStatus' field.
   * Current status of the document (should be CANCELLED)
   * @param value the value to set.
   */
  public void setDocumentStatus(java.lang.String value) {
    this.documentStatus = value;
  }

  /**
   * Gets the value of the 'failureMessages' field.
   * @return List of failure/cancellation reasons
   */
  public java.util.List<java.lang.String> getFailureMessages() {
    return failureMessages;
  }


  /**
   * Sets the value of the 'failureMessages' field.
   * List of failure/cancellation reasons
   * @param value the value to set.
   */
  public void setFailureMessages(java.util.List<java.lang.String> value) {
    this.failureMessages = value;
  }

  /**
   * Gets the value of the 'cancelledAt' field.
   * @return Timestamp when the document was cancelled
   */
  public java.time.Instant getCancelledAt() {
    return cancelledAt;
  }


  /**
   * Sets the value of the 'cancelledAt' field.
   * Timestamp when the document was cancelled
   * @param value the value to set.
   */
  public void setCancelledAt(java.time.Instant value) {
    this.cancelledAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new DocumentCancelledEventAvroModel RecordBuilder.
   * @return A new DocumentCancelledEventAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder newBuilder() {
    return new com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder();
  }

  /**
   * Creates a new DocumentCancelledEventAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DocumentCancelledEventAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder newBuilder(com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder other) {
    if (other == null) {
      return new com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder();
    } else {
      return new com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new DocumentCancelledEventAvroModel RecordBuilder by copying an existing DocumentCancelledEventAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new DocumentCancelledEventAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder newBuilder(com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel other) {
    if (other == null) {
      return new com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder();
    } else {
      return new com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for DocumentCancelledEventAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocumentCancelledEventAvroModel>
    implements org.apache.avro.data.RecordBuilder<DocumentCancelledEventAvroModel> {

    /** Unique identifier for the document */
    private java.lang.String id;
    /** Customer identifier */
    private java.lang.String customerId;
    /** Account identifier */
    private java.lang.String accountId;
    /** Current status of the document (should be CANCELLED) */
    private java.lang.String documentStatus;
    /** List of failure/cancellation reasons */
    private java.util.List<java.lang.String> failureMessages;
    /** Timestamp when the document was cancelled */
    private java.time.Instant cancelledAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.accountId)) {
        this.accountId = data().deepCopy(fields()[2].schema(), other.accountId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.documentStatus)) {
        this.documentStatus = data().deepCopy(fields()[3].schema(), other.documentStatus);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.failureMessages)) {
        this.failureMessages = data().deepCopy(fields()[4].schema(), other.failureMessages);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.cancelledAt)) {
        this.cancelledAt = data().deepCopy(fields()[5].schema(), other.cancelledAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing DocumentCancelledEventAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.accountId)) {
        this.accountId = data().deepCopy(fields()[2].schema(), other.accountId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.documentStatus)) {
        this.documentStatus = data().deepCopy(fields()[3].schema(), other.documentStatus);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.failureMessages)) {
        this.failureMessages = data().deepCopy(fields()[4].schema(), other.failureMessages);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.cancelledAt)) {
        this.cancelledAt = data().deepCopy(fields()[5].schema(), other.cancelledAt);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * Unique identifier for the document
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * Unique identifier for the document
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Unique identifier for the document
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Unique identifier for the document
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerId' field.
      * Customer identifier
      * @return The value.
      */
    public java.lang.String getCustomerId() {
      return customerId;
    }


    /**
      * Sets the value of the 'customerId' field.
      * Customer identifier
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder setCustomerId(java.lang.String value) {
      validate(fields()[1], value);
      this.customerId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * Customer identifier
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerId' field.
      * Customer identifier
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder clearCustomerId() {
      customerId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountId' field.
      * Account identifier
      * @return The value.
      */
    public java.lang.String getAccountId() {
      return accountId;
    }


    /**
      * Sets the value of the 'accountId' field.
      * Account identifier
      * @param value The value of 'accountId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder setAccountId(java.lang.String value) {
      validate(fields()[2], value);
      this.accountId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'accountId' field has been set.
      * Account identifier
      * @return True if the 'accountId' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'accountId' field.
      * Account identifier
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder clearAccountId() {
      accountId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentStatus' field.
      * Current status of the document (should be CANCELLED)
      * @return The value.
      */
    public java.lang.String getDocumentStatus() {
      return documentStatus;
    }


    /**
      * Sets the value of the 'documentStatus' field.
      * Current status of the document (should be CANCELLED)
      * @param value The value of 'documentStatus'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder setDocumentStatus(java.lang.String value) {
      validate(fields()[3], value);
      this.documentStatus = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'documentStatus' field has been set.
      * Current status of the document (should be CANCELLED)
      * @return True if the 'documentStatus' field has been set, false otherwise.
      */
    public boolean hasDocumentStatus() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'documentStatus' field.
      * Current status of the document (should be CANCELLED)
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder clearDocumentStatus() {
      documentStatus = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'failureMessages' field.
      * List of failure/cancellation reasons
      * @return The value.
      */
    public java.util.List<java.lang.String> getFailureMessages() {
      return failureMessages;
    }


    /**
      * Sets the value of the 'failureMessages' field.
      * List of failure/cancellation reasons
      * @param value The value of 'failureMessages'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder setFailureMessages(java.util.List<java.lang.String> value) {
      validate(fields()[4], value);
      this.failureMessages = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'failureMessages' field has been set.
      * List of failure/cancellation reasons
      * @return True if the 'failureMessages' field has been set, false otherwise.
      */
    public boolean hasFailureMessages() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'failureMessages' field.
      * List of failure/cancellation reasons
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder clearFailureMessages() {
      failureMessages = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'cancelledAt' field.
      * Timestamp when the document was cancelled
      * @return The value.
      */
    public java.time.Instant getCancelledAt() {
      return cancelledAt;
    }


    /**
      * Sets the value of the 'cancelledAt' field.
      * Timestamp when the document was cancelled
      * @param value The value of 'cancelledAt'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder setCancelledAt(java.time.Instant value) {
      validate(fields()[5], value);
      this.cancelledAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'cancelledAt' field has been set.
      * Timestamp when the document was cancelled
      * @return True if the 'cancelledAt' field has been set, false otherwise.
      */
    public boolean hasCancelledAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'cancelledAt' field.
      * Timestamp when the document was cancelled
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentCancelledEventAvroModel.Builder clearCancelledAt() {
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DocumentCancelledEventAvroModel build() {
      try {
        DocumentCancelledEventAvroModel record = new DocumentCancelledEventAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.customerId = fieldSetFlags()[1] ? this.customerId : (java.lang.String) defaultValue(fields()[1]);
        record.accountId = fieldSetFlags()[2] ? this.accountId : (java.lang.String) defaultValue(fields()[2]);
        record.documentStatus = fieldSetFlags()[3] ? this.documentStatus : (java.lang.String) defaultValue(fields()[3]);
        record.failureMessages = fieldSetFlags()[4] ? this.failureMessages : (java.util.List<java.lang.String>) defaultValue(fields()[4]);
        record.cancelledAt = fieldSetFlags()[5] ? this.cancelledAt : (java.time.Instant) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DocumentCancelledEventAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<DocumentCancelledEventAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DocumentCancelledEventAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<DocumentCancelledEventAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










