/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.document.notification.system.kafka.document.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Event published when a document has been sent to the customer */
@org.apache.avro.specific.AvroGenerated
public class DocumentSentEventAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4733168141207098613L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DocumentSentEventAvroModel\",\"namespace\":\"com.document.notification.system.kafka.document.avro.model\",\"doc\":\"Event published when a document has been sent to the customer\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"doc\":\"Unique identifier for the document\"},{\"name\":\"customerId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"doc\":\"Customer identifier\"},{\"name\":\"accountId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"},\"doc\":\"Account identifier\"},{\"name\":\"fileName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Name of the sent document file\"},{\"name\":\"documentType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Type of document (PDF, CSV, XML)\"},{\"name\":\"documentStatus\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Current status of the document (should be SENT)\"},{\"name\":\"deliveryStreet\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Delivery street address\"},{\"name\":\"deliveryCity\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Delivery city\"},{\"name\":\"deliveryState\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Delivery state\",\"default\":null},{\"name\":\"deliveryCountry\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Delivery country\"},{\"name\":\"deliveryPostalCode\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"Delivery postal code\",\"default\":null},{\"name\":\"sentAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"},\"doc\":\"Timestamp when the document was sent\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<DocumentSentEventAvroModel> ENCODER =
      new BinaryMessageEncoder<DocumentSentEventAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DocumentSentEventAvroModel> DECODER =
      new BinaryMessageDecoder<DocumentSentEventAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DocumentSentEventAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DocumentSentEventAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DocumentSentEventAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DocumentSentEventAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DocumentSentEventAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DocumentSentEventAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DocumentSentEventAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DocumentSentEventAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Unique identifier for the document */
  private java.lang.String id;
  /** Customer identifier */
  private java.lang.String customerId;
  /** Account identifier */
  private java.lang.String accountId;
  /** Name of the sent document file */
  private java.lang.String fileName;
  /** Type of document (PDF, CSV, XML) */
  private java.lang.String documentType;
  /** Current status of the document (should be SENT) */
  private java.lang.String documentStatus;
  /** Delivery street address */
  private java.lang.String deliveryStreet;
  /** Delivery city */
  private java.lang.String deliveryCity;
  /** Delivery state */
  private java.lang.String deliveryState;
  /** Delivery country */
  private java.lang.String deliveryCountry;
  /** Delivery postal code */
  private java.lang.String deliveryPostalCode;
  /** Timestamp when the document was sent */
  private java.time.Instant sentAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DocumentSentEventAvroModel() {}

  /**
   * All-args constructor.
   * @param id Unique identifier for the document
   * @param customerId Customer identifier
   * @param accountId Account identifier
   * @param fileName Name of the sent document file
   * @param documentType Type of document (PDF, CSV, XML)
   * @param documentStatus Current status of the document (should be SENT)
   * @param deliveryStreet Delivery street address
   * @param deliveryCity Delivery city
   * @param deliveryState Delivery state
   * @param deliveryCountry Delivery country
   * @param deliveryPostalCode Delivery postal code
   * @param sentAt Timestamp when the document was sent
   */
  public DocumentSentEventAvroModel(java.lang.String id, java.lang.String customerId, java.lang.String accountId, java.lang.String fileName, java.lang.String documentType, java.lang.String documentStatus, java.lang.String deliveryStreet, java.lang.String deliveryCity, java.lang.String deliveryState, java.lang.String deliveryCountry, java.lang.String deliveryPostalCode, java.time.Instant sentAt) {
    this.id = id;
    this.customerId = customerId;
    this.accountId = accountId;
    this.fileName = fileName;
    this.documentType = documentType;
    this.documentStatus = documentStatus;
    this.deliveryStreet = deliveryStreet;
    this.deliveryCity = deliveryCity;
    this.deliveryState = deliveryState;
    this.deliveryCountry = deliveryCountry;
    this.deliveryPostalCode = deliveryPostalCode;
    this.sentAt = sentAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return customerId;
    case 2: return accountId;
    case 3: return fileName;
    case 4: return documentType;
    case 5: return documentStatus;
    case 6: return deliveryStreet;
    case 7: return deliveryCity;
    case 8: return deliveryState;
    case 9: return deliveryCountry;
    case 10: return deliveryPostalCode;
    case 11: return sentAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: customerId = value$ != null ? value$.toString() : null; break;
    case 2: accountId = value$ != null ? value$.toString() : null; break;
    case 3: fileName = value$ != null ? value$.toString() : null; break;
    case 4: documentType = value$ != null ? value$.toString() : null; break;
    case 5: documentStatus = value$ != null ? value$.toString() : null; break;
    case 6: deliveryStreet = value$ != null ? value$.toString() : null; break;
    case 7: deliveryCity = value$ != null ? value$.toString() : null; break;
    case 8: deliveryState = value$ != null ? value$.toString() : null; break;
    case 9: deliveryCountry = value$ != null ? value$.toString() : null; break;
    case 10: deliveryPostalCode = value$ != null ? value$.toString() : null; break;
    case 11: sentAt = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return Unique identifier for the document
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * Unique identifier for the document
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return Customer identifier
   */
  public java.lang.String getCustomerId() {
    return customerId;
  }


  /**
   * Sets the value of the 'customerId' field.
   * Customer identifier
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.String value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'accountId' field.
   * @return Account identifier
   */
  public java.lang.String getAccountId() {
    return accountId;
  }


  /**
   * Sets the value of the 'accountId' field.
   * Account identifier
   * @param value the value to set.
   */
  public void setAccountId(java.lang.String value) {
    this.accountId = value;
  }

  /**
   * Gets the value of the 'fileName' field.
   * @return Name of the sent document file
   */
  public java.lang.String getFileName() {
    return fileName;
  }


  /**
   * Sets the value of the 'fileName' field.
   * Name of the sent document file
   * @param value the value to set.
   */
  public void setFileName(java.lang.String value) {
    this.fileName = value;
  }

  /**
   * Gets the value of the 'documentType' field.
   * @return Type of document (PDF, CSV, XML)
   */
  public java.lang.String getDocumentType() {
    return documentType;
  }


  /**
   * Sets the value of the 'documentType' field.
   * Type of document (PDF, CSV, XML)
   * @param value the value to set.
   */
  public void setDocumentType(java.lang.String value) {
    this.documentType = value;
  }

  /**
   * Gets the value of the 'documentStatus' field.
   * @return Current status of the document (should be SENT)
   */
  public java.lang.String getDocumentStatus() {
    return documentStatus;
  }


  /**
   * Sets the value of the 'documentStatus' field.
   * Current status of the document (should be SENT)
   * @param value the value to set.
   */
  public void setDocumentStatus(java.lang.String value) {
    this.documentStatus = value;
  }

  /**
   * Gets the value of the 'deliveryStreet' field.
   * @return Delivery street address
   */
  public java.lang.String getDeliveryStreet() {
    return deliveryStreet;
  }


  /**
   * Sets the value of the 'deliveryStreet' field.
   * Delivery street address
   * @param value the value to set.
   */
  public void setDeliveryStreet(java.lang.String value) {
    this.deliveryStreet = value;
  }

  /**
   * Gets the value of the 'deliveryCity' field.
   * @return Delivery city
   */
  public java.lang.String getDeliveryCity() {
    return deliveryCity;
  }


  /**
   * Sets the value of the 'deliveryCity' field.
   * Delivery city
   * @param value the value to set.
   */
  public void setDeliveryCity(java.lang.String value) {
    this.deliveryCity = value;
  }

  /**
   * Gets the value of the 'deliveryState' field.
   * @return Delivery state
   */
  public java.lang.String getDeliveryState() {
    return deliveryState;
  }


  /**
   * Sets the value of the 'deliveryState' field.
   * Delivery state
   * @param value the value to set.
   */
  public void setDeliveryState(java.lang.String value) {
    this.deliveryState = value;
  }

  /**
   * Gets the value of the 'deliveryCountry' field.
   * @return Delivery country
   */
  public java.lang.String getDeliveryCountry() {
    return deliveryCountry;
  }


  /**
   * Sets the value of the 'deliveryCountry' field.
   * Delivery country
   * @param value the value to set.
   */
  public void setDeliveryCountry(java.lang.String value) {
    this.deliveryCountry = value;
  }

  /**
   * Gets the value of the 'deliveryPostalCode' field.
   * @return Delivery postal code
   */
  public java.lang.String getDeliveryPostalCode() {
    return deliveryPostalCode;
  }


  /**
   * Sets the value of the 'deliveryPostalCode' field.
   * Delivery postal code
   * @param value the value to set.
   */
  public void setDeliveryPostalCode(java.lang.String value) {
    this.deliveryPostalCode = value;
  }

  /**
   * Gets the value of the 'sentAt' field.
   * @return Timestamp when the document was sent
   */
  public java.time.Instant getSentAt() {
    return sentAt;
  }


  /**
   * Sets the value of the 'sentAt' field.
   * Timestamp when the document was sent
   * @param value the value to set.
   */
  public void setSentAt(java.time.Instant value) {
    this.sentAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new DocumentSentEventAvroModel RecordBuilder.
   * @return A new DocumentSentEventAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder newBuilder() {
    return new com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder();
  }

  /**
   * Creates a new DocumentSentEventAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DocumentSentEventAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder newBuilder(com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder other) {
    if (other == null) {
      return new com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder();
    } else {
      return new com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new DocumentSentEventAvroModel RecordBuilder by copying an existing DocumentSentEventAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new DocumentSentEventAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder newBuilder(com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel other) {
    if (other == null) {
      return new com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder();
    } else {
      return new com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for DocumentSentEventAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DocumentSentEventAvroModel>
    implements org.apache.avro.data.RecordBuilder<DocumentSentEventAvroModel> {

    /** Unique identifier for the document */
    private java.lang.String id;
    /** Customer identifier */
    private java.lang.String customerId;
    /** Account identifier */
    private java.lang.String accountId;
    /** Name of the sent document file */
    private java.lang.String fileName;
    /** Type of document (PDF, CSV, XML) */
    private java.lang.String documentType;
    /** Current status of the document (should be SENT) */
    private java.lang.String documentStatus;
    /** Delivery street address */
    private java.lang.String deliveryStreet;
    /** Delivery city */
    private java.lang.String deliveryCity;
    /** Delivery state */
    private java.lang.String deliveryState;
    /** Delivery country */
    private java.lang.String deliveryCountry;
    /** Delivery postal code */
    private java.lang.String deliveryPostalCode;
    /** Timestamp when the document was sent */
    private java.time.Instant sentAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.accountId)) {
        this.accountId = data().deepCopy(fields()[2].schema(), other.accountId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.fileName)) {
        this.fileName = data().deepCopy(fields()[3].schema(), other.fileName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.documentType)) {
        this.documentType = data().deepCopy(fields()[4].schema(), other.documentType);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.documentStatus)) {
        this.documentStatus = data().deepCopy(fields()[5].schema(), other.documentStatus);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.deliveryStreet)) {
        this.deliveryStreet = data().deepCopy(fields()[6].schema(), other.deliveryStreet);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.deliveryCity)) {
        this.deliveryCity = data().deepCopy(fields()[7].schema(), other.deliveryCity);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.deliveryState)) {
        this.deliveryState = data().deepCopy(fields()[8].schema(), other.deliveryState);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.deliveryCountry)) {
        this.deliveryCountry = data().deepCopy(fields()[9].schema(), other.deliveryCountry);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.deliveryPostalCode)) {
        this.deliveryPostalCode = data().deepCopy(fields()[10].schema(), other.deliveryPostalCode);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.sentAt)) {
        this.sentAt = data().deepCopy(fields()[11].schema(), other.sentAt);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing DocumentSentEventAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.customerId)) {
        this.customerId = data().deepCopy(fields()[1].schema(), other.customerId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.accountId)) {
        this.accountId = data().deepCopy(fields()[2].schema(), other.accountId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.fileName)) {
        this.fileName = data().deepCopy(fields()[3].schema(), other.fileName);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.documentType)) {
        this.documentType = data().deepCopy(fields()[4].schema(), other.documentType);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.documentStatus)) {
        this.documentStatus = data().deepCopy(fields()[5].schema(), other.documentStatus);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.deliveryStreet)) {
        this.deliveryStreet = data().deepCopy(fields()[6].schema(), other.deliveryStreet);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.deliveryCity)) {
        this.deliveryCity = data().deepCopy(fields()[7].schema(), other.deliveryCity);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.deliveryState)) {
        this.deliveryState = data().deepCopy(fields()[8].schema(), other.deliveryState);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.deliveryCountry)) {
        this.deliveryCountry = data().deepCopy(fields()[9].schema(), other.deliveryCountry);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.deliveryPostalCode)) {
        this.deliveryPostalCode = data().deepCopy(fields()[10].schema(), other.deliveryPostalCode);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.sentAt)) {
        this.sentAt = data().deepCopy(fields()[11].schema(), other.sentAt);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * Unique identifier for the document
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * Unique identifier for the document
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * Unique identifier for the document
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * Unique identifier for the document
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerId' field.
      * Customer identifier
      * @return The value.
      */
    public java.lang.String getCustomerId() {
      return customerId;
    }


    /**
      * Sets the value of the 'customerId' field.
      * Customer identifier
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder setCustomerId(java.lang.String value) {
      validate(fields()[1], value);
      this.customerId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * Customer identifier
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'customerId' field.
      * Customer identifier
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder clearCustomerId() {
      customerId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'accountId' field.
      * Account identifier
      * @return The value.
      */
    public java.lang.String getAccountId() {
      return accountId;
    }


    /**
      * Sets the value of the 'accountId' field.
      * Account identifier
      * @param value The value of 'accountId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder setAccountId(java.lang.String value) {
      validate(fields()[2], value);
      this.accountId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'accountId' field has been set.
      * Account identifier
      * @return True if the 'accountId' field has been set, false otherwise.
      */
    public boolean hasAccountId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'accountId' field.
      * Account identifier
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder clearAccountId() {
      accountId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'fileName' field.
      * Name of the sent document file
      * @return The value.
      */
    public java.lang.String getFileName() {
      return fileName;
    }


    /**
      * Sets the value of the 'fileName' field.
      * Name of the sent document file
      * @param value The value of 'fileName'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder setFileName(java.lang.String value) {
      validate(fields()[3], value);
      this.fileName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'fileName' field has been set.
      * Name of the sent document file
      * @return True if the 'fileName' field has been set, false otherwise.
      */
    public boolean hasFileName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'fileName' field.
      * Name of the sent document file
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder clearFileName() {
      fileName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentType' field.
      * Type of document (PDF, CSV, XML)
      * @return The value.
      */
    public java.lang.String getDocumentType() {
      return documentType;
    }


    /**
      * Sets the value of the 'documentType' field.
      * Type of document (PDF, CSV, XML)
      * @param value The value of 'documentType'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder setDocumentType(java.lang.String value) {
      validate(fields()[4], value);
      this.documentType = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'documentType' field has been set.
      * Type of document (PDF, CSV, XML)
      * @return True if the 'documentType' field has been set, false otherwise.
      */
    public boolean hasDocumentType() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'documentType' field.
      * Type of document (PDF, CSV, XML)
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder clearDocumentType() {
      documentType = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentStatus' field.
      * Current status of the document (should be SENT)
      * @return The value.
      */
    public java.lang.String getDocumentStatus() {
      return documentStatus;
    }


    /**
      * Sets the value of the 'documentStatus' field.
      * Current status of the document (should be SENT)
      * @param value The value of 'documentStatus'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder setDocumentStatus(java.lang.String value) {
      validate(fields()[5], value);
      this.documentStatus = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'documentStatus' field has been set.
      * Current status of the document (should be SENT)
      * @return True if the 'documentStatus' field has been set, false otherwise.
      */
    public boolean hasDocumentStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'documentStatus' field.
      * Current status of the document (should be SENT)
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder clearDocumentStatus() {
      documentStatus = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'deliveryStreet' field.
      * Delivery street address
      * @return The value.
      */
    public java.lang.String getDeliveryStreet() {
      return deliveryStreet;
    }


    /**
      * Sets the value of the 'deliveryStreet' field.
      * Delivery street address
      * @param value The value of 'deliveryStreet'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder setDeliveryStreet(java.lang.String value) {
      validate(fields()[6], value);
      this.deliveryStreet = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'deliveryStreet' field has been set.
      * Delivery street address
      * @return True if the 'deliveryStreet' field has been set, false otherwise.
      */
    public boolean hasDeliveryStreet() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'deliveryStreet' field.
      * Delivery street address
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder clearDeliveryStreet() {
      deliveryStreet = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'deliveryCity' field.
      * Delivery city
      * @return The value.
      */
    public java.lang.String getDeliveryCity() {
      return deliveryCity;
    }


    /**
      * Sets the value of the 'deliveryCity' field.
      * Delivery city
      * @param value The value of 'deliveryCity'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder setDeliveryCity(java.lang.String value) {
      validate(fields()[7], value);
      this.deliveryCity = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'deliveryCity' field has been set.
      * Delivery city
      * @return True if the 'deliveryCity' field has been set, false otherwise.
      */
    public boolean hasDeliveryCity() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'deliveryCity' field.
      * Delivery city
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder clearDeliveryCity() {
      deliveryCity = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'deliveryState' field.
      * Delivery state
      * @return The value.
      */
    public java.lang.String getDeliveryState() {
      return deliveryState;
    }


    /**
      * Sets the value of the 'deliveryState' field.
      * Delivery state
      * @param value The value of 'deliveryState'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder setDeliveryState(java.lang.String value) {
      validate(fields()[8], value);
      this.deliveryState = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'deliveryState' field has been set.
      * Delivery state
      * @return True if the 'deliveryState' field has been set, false otherwise.
      */
    public boolean hasDeliveryState() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'deliveryState' field.
      * Delivery state
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder clearDeliveryState() {
      deliveryState = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'deliveryCountry' field.
      * Delivery country
      * @return The value.
      */
    public java.lang.String getDeliveryCountry() {
      return deliveryCountry;
    }


    /**
      * Sets the value of the 'deliveryCountry' field.
      * Delivery country
      * @param value The value of 'deliveryCountry'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder setDeliveryCountry(java.lang.String value) {
      validate(fields()[9], value);
      this.deliveryCountry = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'deliveryCountry' field has been set.
      * Delivery country
      * @return True if the 'deliveryCountry' field has been set, false otherwise.
      */
    public boolean hasDeliveryCountry() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'deliveryCountry' field.
      * Delivery country
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder clearDeliveryCountry() {
      deliveryCountry = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'deliveryPostalCode' field.
      * Delivery postal code
      * @return The value.
      */
    public java.lang.String getDeliveryPostalCode() {
      return deliveryPostalCode;
    }


    /**
      * Sets the value of the 'deliveryPostalCode' field.
      * Delivery postal code
      * @param value The value of 'deliveryPostalCode'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder setDeliveryPostalCode(java.lang.String value) {
      validate(fields()[10], value);
      this.deliveryPostalCode = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'deliveryPostalCode' field has been set.
      * Delivery postal code
      * @return True if the 'deliveryPostalCode' field has been set, false otherwise.
      */
    public boolean hasDeliveryPostalCode() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'deliveryPostalCode' field.
      * Delivery postal code
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder clearDeliveryPostalCode() {
      deliveryPostalCode = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'sentAt' field.
      * Timestamp when the document was sent
      * @return The value.
      */
    public java.time.Instant getSentAt() {
      return sentAt;
    }


    /**
      * Sets the value of the 'sentAt' field.
      * Timestamp when the document was sent
      * @param value The value of 'sentAt'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder setSentAt(java.time.Instant value) {
      validate(fields()[11], value);
      this.sentAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'sentAt' field has been set.
      * Timestamp when the document was sent
      * @return True if the 'sentAt' field has been set, false otherwise.
      */
    public boolean hasSentAt() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'sentAt' field.
      * Timestamp when the document was sent
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentSentEventAvroModel.Builder clearSentAt() {
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DocumentSentEventAvroModel build() {
      try {
        DocumentSentEventAvroModel record = new DocumentSentEventAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.customerId = fieldSetFlags()[1] ? this.customerId : (java.lang.String) defaultValue(fields()[1]);
        record.accountId = fieldSetFlags()[2] ? this.accountId : (java.lang.String) defaultValue(fields()[2]);
        record.fileName = fieldSetFlags()[3] ? this.fileName : (java.lang.String) defaultValue(fields()[3]);
        record.documentType = fieldSetFlags()[4] ? this.documentType : (java.lang.String) defaultValue(fields()[4]);
        record.documentStatus = fieldSetFlags()[5] ? this.documentStatus : (java.lang.String) defaultValue(fields()[5]);
        record.deliveryStreet = fieldSetFlags()[6] ? this.deliveryStreet : (java.lang.String) defaultValue(fields()[6]);
        record.deliveryCity = fieldSetFlags()[7] ? this.deliveryCity : (java.lang.String) defaultValue(fields()[7]);
        record.deliveryState = fieldSetFlags()[8] ? this.deliveryState : (java.lang.String) defaultValue(fields()[8]);
        record.deliveryCountry = fieldSetFlags()[9] ? this.deliveryCountry : (java.lang.String) defaultValue(fields()[9]);
        record.deliveryPostalCode = fieldSetFlags()[10] ? this.deliveryPostalCode : (java.lang.String) defaultValue(fields()[10]);
        record.sentAt = fieldSetFlags()[11] ? this.sentAt : (java.time.Instant) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DocumentSentEventAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<DocumentSentEventAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DocumentSentEventAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<DocumentSentEventAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










