/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.document.notification.system.kafka.document.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum DocumentGenerationStatus implements org.apache.avro.generic.GenericEnumSymbol<DocumentGenerationStatus> {
  PENDING, CANCELLED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"DocumentGenerationStatus\",\"namespace\":\"com.document.notification.system.kafka.document.avro.model\",\"symbols\":[\"PENDING\",\"CANCELLED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
