/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.document.notification.system.kafka.document.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GeneratorRequestAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1522542996320482759L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GeneratorRequestAvroModel\",\"namespace\":\"com.document.notification.system.kafka.document.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"customerId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"documentId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"documentGenerationStatus\",\"type\":{\"type\":\"enum\",\"name\":\"DocumentGenerationStatus\",\"symbols\":[\"PENDING\",\"CANCELLED\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<GeneratorRequestAvroModel> ENCODER =
      new BinaryMessageEncoder<GeneratorRequestAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GeneratorRequestAvroModel> DECODER =
      new BinaryMessageDecoder<GeneratorRequestAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GeneratorRequestAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GeneratorRequestAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GeneratorRequestAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GeneratorRequestAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GeneratorRequestAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GeneratorRequestAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GeneratorRequestAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GeneratorRequestAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String sagaId;
  private java.lang.String customerId;
  private java.lang.String documentId;
  private java.time.Instant createdAt;
  private com.document.notification.system.kafka.document.avro.model.DocumentGenerationStatus documentGenerationStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GeneratorRequestAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param sagaId The new value for sagaId
   * @param customerId The new value for customerId
   * @param documentId The new value for documentId
   * @param createdAt The new value for createdAt
   * @param documentGenerationStatus The new value for documentGenerationStatus
   */
  public GeneratorRequestAvroModel(java.lang.String id, java.lang.String sagaId, java.lang.String customerId, java.lang.String documentId, java.time.Instant createdAt, com.document.notification.system.kafka.document.avro.model.DocumentGenerationStatus documentGenerationStatus) {
    this.id = id;
    this.sagaId = sagaId;
    this.customerId = customerId;
    this.documentId = documentId;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.documentGenerationStatus = documentGenerationStatus;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return sagaId;
    case 2: return customerId;
    case 3: return documentId;
    case 4: return createdAt;
    case 5: return documentGenerationStatus;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: sagaId = value$ != null ? value$.toString() : null; break;
    case 2: customerId = value$ != null ? value$.toString() : null; break;
    case 3: documentId = value$ != null ? value$.toString() : null; break;
    case 4: createdAt = (java.time.Instant)value$; break;
    case 5: documentGenerationStatus = (com.document.notification.system.kafka.document.avro.model.DocumentGenerationStatus)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'sagaId' field.
   * @return The value of the 'sagaId' field.
   */
  public java.lang.String getSagaId() {
    return sagaId;
  }


  /**
   * Sets the value of the 'sagaId' field.
   * @param value the value to set.
   */
  public void setSagaId(java.lang.String value) {
    this.sagaId = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return The value of the 'customerId' field.
   */
  public java.lang.String getCustomerId() {
    return customerId;
  }


  /**
   * Sets the value of the 'customerId' field.
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.String value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'documentId' field.
   * @return The value of the 'documentId' field.
   */
  public java.lang.String getDocumentId() {
    return documentId;
  }


  /**
   * Sets the value of the 'documentId' field.
   * @param value the value to set.
   */
  public void setDocumentId(java.lang.String value) {
    this.documentId = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'documentGenerationStatus' field.
   * @return The value of the 'documentGenerationStatus' field.
   */
  public com.document.notification.system.kafka.document.avro.model.DocumentGenerationStatus getDocumentGenerationStatus() {
    return documentGenerationStatus;
  }


  /**
   * Sets the value of the 'documentGenerationStatus' field.
   * @param value the value to set.
   */
  public void setDocumentGenerationStatus(com.document.notification.system.kafka.document.avro.model.DocumentGenerationStatus value) {
    this.documentGenerationStatus = value;
  }

  /**
   * Creates a new GeneratorRequestAvroModel RecordBuilder.
   * @return A new GeneratorRequestAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder newBuilder() {
    return new com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder();
  }

  /**
   * Creates a new GeneratorRequestAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GeneratorRequestAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder newBuilder(com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder other) {
    if (other == null) {
      return new com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder();
    } else {
      return new com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new GeneratorRequestAvroModel RecordBuilder by copying an existing GeneratorRequestAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new GeneratorRequestAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder newBuilder(com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel other) {
    if (other == null) {
      return new com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder();
    } else {
      return new com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for GeneratorRequestAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GeneratorRequestAvroModel>
    implements org.apache.avro.data.RecordBuilder<GeneratorRequestAvroModel> {

    private java.lang.String id;
    private java.lang.String sagaId;
    private java.lang.String customerId;
    private java.lang.String documentId;
    private java.time.Instant createdAt;
    private com.document.notification.system.kafka.document.avro.model.DocumentGenerationStatus documentGenerationStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.customerId)) {
        this.customerId = data().deepCopy(fields()[2].schema(), other.customerId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.documentId)) {
        this.documentId = data().deepCopy(fields()[3].schema(), other.documentId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.documentGenerationStatus)) {
        this.documentGenerationStatus = data().deepCopy(fields()[5].schema(), other.documentGenerationStatus);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
    }

    /**
     * Creates a Builder by copying an existing GeneratorRequestAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.customerId)) {
        this.customerId = data().deepCopy(fields()[2].schema(), other.customerId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.documentId)) {
        this.documentId = data().deepCopy(fields()[3].schema(), other.documentId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[4].schema(), other.createdAt);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.documentGenerationStatus)) {
        this.documentGenerationStatus = data().deepCopy(fields()[5].schema(), other.documentGenerationStatus);
        fieldSetFlags()[5] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sagaId' field.
      * @return The value.
      */
    public java.lang.String getSagaId() {
      return sagaId;
    }


    /**
      * Sets the value of the 'sagaId' field.
      * @param value The value of 'sagaId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder setSagaId(java.lang.String value) {
      validate(fields()[1], value);
      this.sagaId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sagaId' field has been set.
      * @return True if the 'sagaId' field has been set, false otherwise.
      */
    public boolean hasSagaId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sagaId' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder clearSagaId() {
      sagaId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerId' field.
      * @return The value.
      */
    public java.lang.String getCustomerId() {
      return customerId;
    }


    /**
      * Sets the value of the 'customerId' field.
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder setCustomerId(java.lang.String value) {
      validate(fields()[2], value);
      this.customerId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'customerId' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder clearCustomerId() {
      customerId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentId' field.
      * @return The value.
      */
    public java.lang.String getDocumentId() {
      return documentId;
    }


    /**
      * Sets the value of the 'documentId' field.
      * @param value The value of 'documentId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder setDocumentId(java.lang.String value) {
      validate(fields()[3], value);
      this.documentId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'documentId' field has been set.
      * @return True if the 'documentId' field has been set, false otherwise.
      */
    public boolean hasDocumentId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'documentId' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder clearDocumentId() {
      documentId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[4], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentGenerationStatus' field.
      * @return The value.
      */
    public com.document.notification.system.kafka.document.avro.model.DocumentGenerationStatus getDocumentGenerationStatus() {
      return documentGenerationStatus;
    }


    /**
      * Sets the value of the 'documentGenerationStatus' field.
      * @param value The value of 'documentGenerationStatus'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder setDocumentGenerationStatus(com.document.notification.system.kafka.document.avro.model.DocumentGenerationStatus value) {
      validate(fields()[5], value);
      this.documentGenerationStatus = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'documentGenerationStatus' field has been set.
      * @return True if the 'documentGenerationStatus' field has been set, false otherwise.
      */
    public boolean hasDocumentGenerationStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'documentGenerationStatus' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorRequestAvroModel.Builder clearDocumentGenerationStatus() {
      documentGenerationStatus = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GeneratorRequestAvroModel build() {
      try {
        GeneratorRequestAvroModel record = new GeneratorRequestAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.sagaId = fieldSetFlags()[1] ? this.sagaId : (java.lang.String) defaultValue(fields()[1]);
        record.customerId = fieldSetFlags()[2] ? this.customerId : (java.lang.String) defaultValue(fields()[2]);
        record.documentId = fieldSetFlags()[3] ? this.documentId : (java.lang.String) defaultValue(fields()[3]);
        record.createdAt = fieldSetFlags()[4] ? this.createdAt : (java.time.Instant) defaultValue(fields()[4]);
        record.documentGenerationStatus = fieldSetFlags()[5] ? this.documentGenerationStatus : (com.document.notification.system.kafka.document.avro.model.DocumentGenerationStatus) defaultValue(fields()[5]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GeneratorRequestAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<GeneratorRequestAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GeneratorRequestAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<GeneratorRequestAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










