/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.document.notification.system.kafka.document.avro.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class GeneratorResponseAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 249057300948029433L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GeneratorResponseAvroModel\",\"namespace\":\"com.document.notification.system.kafka.document.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"generatorId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"customerId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"documentId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"generationStatus\",\"type\":{\"type\":\"enum\",\"name\":\"GenerationStatus\",\"symbols\":[\"GENERATION_COMPLETED\",\"GENERATION_CANCELLED\",\"GENERATION_FAILED\"]}},{\"name\":\"failureMessages\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<GeneratorResponseAvroModel> ENCODER =
      new BinaryMessageEncoder<GeneratorResponseAvroModel>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GeneratorResponseAvroModel> DECODER =
      new BinaryMessageDecoder<GeneratorResponseAvroModel>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GeneratorResponseAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GeneratorResponseAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GeneratorResponseAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<GeneratorResponseAvroModel>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GeneratorResponseAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GeneratorResponseAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GeneratorResponseAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GeneratorResponseAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String id;
  private java.lang.String sagaId;
  private java.lang.String generatorId;
  private java.lang.String customerId;
  private java.lang.String documentId;
  private java.time.Instant createdAt;
  private com.document.notification.system.kafka.document.avro.model.GenerationStatus generationStatus;
  private java.util.List<java.lang.String> failureMessages;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GeneratorResponseAvroModel() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param sagaId The new value for sagaId
   * @param generatorId The new value for generatorId
   * @param customerId The new value for customerId
   * @param documentId The new value for documentId
   * @param createdAt The new value for createdAt
   * @param generationStatus The new value for generationStatus
   * @param failureMessages The new value for failureMessages
   */
  public GeneratorResponseAvroModel(java.lang.String id, java.lang.String sagaId, java.lang.String generatorId, java.lang.String customerId, java.lang.String documentId, java.time.Instant createdAt, com.document.notification.system.kafka.document.avro.model.GenerationStatus generationStatus, java.util.List<java.lang.String> failureMessages) {
    this.id = id;
    this.sagaId = sagaId;
    this.generatorId = generatorId;
    this.customerId = customerId;
    this.documentId = documentId;
    this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.generationStatus = generationStatus;
    this.failureMessages = failureMessages;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return sagaId;
    case 2: return generatorId;
    case 3: return customerId;
    case 4: return documentId;
    case 5: return createdAt;
    case 6: return generationStatus;
    case 7: return failureMessages;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = value$ != null ? value$.toString() : null; break;
    case 1: sagaId = value$ != null ? value$.toString() : null; break;
    case 2: generatorId = value$ != null ? value$.toString() : null; break;
    case 3: customerId = value$ != null ? value$.toString() : null; break;
    case 4: documentId = value$ != null ? value$.toString() : null; break;
    case 5: createdAt = (java.time.Instant)value$; break;
    case 6: generationStatus = (com.document.notification.system.kafka.document.avro.model.GenerationStatus)value$; break;
    case 7: failureMessages = (java.util.List<java.lang.String>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.String getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.String value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'sagaId' field.
   * @return The value of the 'sagaId' field.
   */
  public java.lang.String getSagaId() {
    return sagaId;
  }


  /**
   * Sets the value of the 'sagaId' field.
   * @param value the value to set.
   */
  public void setSagaId(java.lang.String value) {
    this.sagaId = value;
  }

  /**
   * Gets the value of the 'generatorId' field.
   * @return The value of the 'generatorId' field.
   */
  public java.lang.String getGeneratorId() {
    return generatorId;
  }


  /**
   * Sets the value of the 'generatorId' field.
   * @param value the value to set.
   */
  public void setGeneratorId(java.lang.String value) {
    this.generatorId = value;
  }

  /**
   * Gets the value of the 'customerId' field.
   * @return The value of the 'customerId' field.
   */
  public java.lang.String getCustomerId() {
    return customerId;
  }


  /**
   * Sets the value of the 'customerId' field.
   * @param value the value to set.
   */
  public void setCustomerId(java.lang.String value) {
    this.customerId = value;
  }

  /**
   * Gets the value of the 'documentId' field.
   * @return The value of the 'documentId' field.
   */
  public java.lang.String getDocumentId() {
    return documentId;
  }


  /**
   * Sets the value of the 'documentId' field.
   * @param value the value to set.
   */
  public void setDocumentId(java.lang.String value) {
    this.documentId = value;
  }

  /**
   * Gets the value of the 'createdAt' field.
   * @return The value of the 'createdAt' field.
   */
  public java.time.Instant getCreatedAt() {
    return createdAt;
  }


  /**
   * Sets the value of the 'createdAt' field.
   * @param value the value to set.
   */
  public void setCreatedAt(java.time.Instant value) {
    this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'generationStatus' field.
   * @return The value of the 'generationStatus' field.
   */
  public com.document.notification.system.kafka.document.avro.model.GenerationStatus getGenerationStatus() {
    return generationStatus;
  }


  /**
   * Sets the value of the 'generationStatus' field.
   * @param value the value to set.
   */
  public void setGenerationStatus(com.document.notification.system.kafka.document.avro.model.GenerationStatus value) {
    this.generationStatus = value;
  }

  /**
   * Gets the value of the 'failureMessages' field.
   * @return The value of the 'failureMessages' field.
   */
  public java.util.List<java.lang.String> getFailureMessages() {
    return failureMessages;
  }


  /**
   * Sets the value of the 'failureMessages' field.
   * @param value the value to set.
   */
  public void setFailureMessages(java.util.List<java.lang.String> value) {
    this.failureMessages = value;
  }

  /**
   * Creates a new GeneratorResponseAvroModel RecordBuilder.
   * @return A new GeneratorResponseAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder newBuilder() {
    return new com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder();
  }

  /**
   * Creates a new GeneratorResponseAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GeneratorResponseAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder newBuilder(com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder other) {
    if (other == null) {
      return new com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder();
    } else {
      return new com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new GeneratorResponseAvroModel RecordBuilder by copying an existing GeneratorResponseAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new GeneratorResponseAvroModel RecordBuilder
   */
  public static com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder newBuilder(com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel other) {
    if (other == null) {
      return new com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder();
    } else {
      return new com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for GeneratorResponseAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GeneratorResponseAvroModel>
    implements org.apache.avro.data.RecordBuilder<GeneratorResponseAvroModel> {

    private java.lang.String id;
    private java.lang.String sagaId;
    private java.lang.String generatorId;
    private java.lang.String customerId;
    private java.lang.String documentId;
    private java.time.Instant createdAt;
    private com.document.notification.system.kafka.document.avro.model.GenerationStatus generationStatus;
    private java.util.List<java.lang.String> failureMessages;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.generatorId)) {
        this.generatorId = data().deepCopy(fields()[2].schema(), other.generatorId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.customerId)) {
        this.customerId = data().deepCopy(fields()[3].schema(), other.customerId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.documentId)) {
        this.documentId = data().deepCopy(fields()[4].schema(), other.documentId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.generationStatus)) {
        this.generationStatus = data().deepCopy(fields()[6].schema(), other.generationStatus);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.failureMessages)) {
        this.failureMessages = data().deepCopy(fields()[7].schema(), other.failureMessages);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
    }

    /**
     * Creates a Builder by copying an existing GeneratorResponseAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.sagaId)) {
        this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.generatorId)) {
        this.generatorId = data().deepCopy(fields()[2].schema(), other.generatorId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.customerId)) {
        this.customerId = data().deepCopy(fields()[3].schema(), other.customerId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.documentId)) {
        this.documentId = data().deepCopy(fields()[4].schema(), other.documentId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.createdAt)) {
        this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.generationStatus)) {
        this.generationStatus = data().deepCopy(fields()[6].schema(), other.generationStatus);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.failureMessages)) {
        this.failureMessages = data().deepCopy(fields()[7].schema(), other.failureMessages);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.String getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder setId(java.lang.String value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'sagaId' field.
      * @return The value.
      */
    public java.lang.String getSagaId() {
      return sagaId;
    }


    /**
      * Sets the value of the 'sagaId' field.
      * @param value The value of 'sagaId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder setSagaId(java.lang.String value) {
      validate(fields()[1], value);
      this.sagaId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'sagaId' field has been set.
      * @return True if the 'sagaId' field has been set, false otherwise.
      */
    public boolean hasSagaId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'sagaId' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder clearSagaId() {
      sagaId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'generatorId' field.
      * @return The value.
      */
    public java.lang.String getGeneratorId() {
      return generatorId;
    }


    /**
      * Sets the value of the 'generatorId' field.
      * @param value The value of 'generatorId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder setGeneratorId(java.lang.String value) {
      validate(fields()[2], value);
      this.generatorId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'generatorId' field has been set.
      * @return True if the 'generatorId' field has been set, false otherwise.
      */
    public boolean hasGeneratorId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'generatorId' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder clearGeneratorId() {
      generatorId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerId' field.
      * @return The value.
      */
    public java.lang.String getCustomerId() {
      return customerId;
    }


    /**
      * Sets the value of the 'customerId' field.
      * @param value The value of 'customerId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder setCustomerId(java.lang.String value) {
      validate(fields()[3], value);
      this.customerId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'customerId' field has been set.
      * @return True if the 'customerId' field has been set, false otherwise.
      */
    public boolean hasCustomerId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'customerId' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder clearCustomerId() {
      customerId = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'documentId' field.
      * @return The value.
      */
    public java.lang.String getDocumentId() {
      return documentId;
    }


    /**
      * Sets the value of the 'documentId' field.
      * @param value The value of 'documentId'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder setDocumentId(java.lang.String value) {
      validate(fields()[4], value);
      this.documentId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'documentId' field has been set.
      * @return True if the 'documentId' field has been set, false otherwise.
      */
    public boolean hasDocumentId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'documentId' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder clearDocumentId() {
      documentId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdAt' field.
      * @return The value.
      */
    public java.time.Instant getCreatedAt() {
      return createdAt;
    }


    /**
      * Sets the value of the 'createdAt' field.
      * @param value The value of 'createdAt'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder setCreatedAt(java.time.Instant value) {
      validate(fields()[5], value);
      this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'createdAt' field has been set.
      * @return True if the 'createdAt' field has been set, false otherwise.
      */
    public boolean hasCreatedAt() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'createdAt' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder clearCreatedAt() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'generationStatus' field.
      * @return The value.
      */
    public com.document.notification.system.kafka.document.avro.model.GenerationStatus getGenerationStatus() {
      return generationStatus;
    }


    /**
      * Sets the value of the 'generationStatus' field.
      * @param value The value of 'generationStatus'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder setGenerationStatus(com.document.notification.system.kafka.document.avro.model.GenerationStatus value) {
      validate(fields()[6], value);
      this.generationStatus = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'generationStatus' field has been set.
      * @return True if the 'generationStatus' field has been set, false otherwise.
      */
    public boolean hasGenerationStatus() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'generationStatus' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder clearGenerationStatus() {
      generationStatus = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'failureMessages' field.
      * @return The value.
      */
    public java.util.List<java.lang.String> getFailureMessages() {
      return failureMessages;
    }


    /**
      * Sets the value of the 'failureMessages' field.
      * @param value The value of 'failureMessages'.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder setFailureMessages(java.util.List<java.lang.String> value) {
      validate(fields()[7], value);
      this.failureMessages = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'failureMessages' field has been set.
      * @return True if the 'failureMessages' field has been set, false otherwise.
      */
    public boolean hasFailureMessages() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'failureMessages' field.
      * @return This builder.
      */
    public com.document.notification.system.kafka.document.avro.model.GeneratorResponseAvroModel.Builder clearFailureMessages() {
      failureMessages = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GeneratorResponseAvroModel build() {
      try {
        GeneratorResponseAvroModel record = new GeneratorResponseAvroModel();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
        record.sagaId = fieldSetFlags()[1] ? this.sagaId : (java.lang.String) defaultValue(fields()[1]);
        record.generatorId = fieldSetFlags()[2] ? this.generatorId : (java.lang.String) defaultValue(fields()[2]);
        record.customerId = fieldSetFlags()[3] ? this.customerId : (java.lang.String) defaultValue(fields()[3]);
        record.documentId = fieldSetFlags()[4] ? this.documentId : (java.lang.String) defaultValue(fields()[4]);
        record.createdAt = fieldSetFlags()[5] ? this.createdAt : (java.time.Instant) defaultValue(fields()[5]);
        record.generationStatus = fieldSetFlags()[6] ? this.generationStatus : (com.document.notification.system.kafka.document.avro.model.GenerationStatus) defaultValue(fields()[6]);
        record.failureMessages = fieldSetFlags()[7] ? this.failureMessages : (java.util.List<java.lang.String>) defaultValue(fields()[7]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GeneratorResponseAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<GeneratorResponseAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GeneratorResponseAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<GeneratorResponseAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










