/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.document.notification.system.kafka.document.avro.model;
@org.apache.avro.specific.AvroGenerated
public enum GenerationStatus implements org.apache.avro.generic.GenericEnumSymbol<GenerationStatus> {
  GENERATION_COMPLETED, GENERATION_CANCELLED, GENERATION_FAILED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"GenerationStatus\",\"namespace\":\"com.document.notification.system.kafka.document.avro.model\",\"symbols\":[\"GENERATION_COMPLETED\",\"GENERATION_CANCELLED\",\"GENERATION_FAILED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
