/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.document.notification.system.kafka.document.avro.model;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class NotificationResponseAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"NotificationResponseAvroModel\",\"namespace\":\"com.document.notification.system.kafka.document.avro.model\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"sagaId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"notificationId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"documentId\",\"type\":{\"type\":\"string\",\"logicalType\":\"uuid\"}},{\"name\":\"recipientId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"Notification target that was processed\"},{\"name\":\"createdAt\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"notificationStatus\",\"type\":{\"type\":\"enum\",\"name\":\"NotificationStatus\",\"symbols\":[\"NOTIFICATION_PENDING\",\"NOTIFICATION_SENT\",\"NOTIFICATION_CANCELLED\",\"NOTIFICATION_FAILED\"]},\"doc\":\"Final processing status returned by notification-service\"},{\"name\":\"failureMessages\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},\"doc\":\"Business or technical errors produced while sending the notification\"}]}");
    private static final long serialVersionUID = -7174794808272310586L;
    private static final SpecificData MODEL$ = new SpecificData();
    private static final BinaryMessageEncoder<NotificationResponseAvroModel> ENCODER =
            new BinaryMessageEncoder<NotificationResponseAvroModel>(MODEL$, SCHEMA$);
    private static final BinaryMessageDecoder<NotificationResponseAvroModel> DECODER =
            new BinaryMessageDecoder<NotificationResponseAvroModel>(MODEL$, SCHEMA$);
    private static final org.apache.avro.Conversion<?>[] conversions =
            new org.apache.avro.Conversion<?>[]{
                    null,
                    null,
                    null,
                    null,
                    null,
                    new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
                    null,
                    null,
                    null
            };
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<NotificationResponseAvroModel>
            WRITER$ = (org.apache.avro.io.DatumWriter<NotificationResponseAvroModel>) MODEL$.createDatumWriter(SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<NotificationResponseAvroModel>
            READER$ = (org.apache.avro.io.DatumReader<NotificationResponseAvroModel>) MODEL$.createDatumReader(SCHEMA$);

    static {
        MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
    }

    private java.lang.String id;
    private java.lang.String sagaId;
    private java.lang.String notificationId;
    private java.lang.String documentId;
    /** Notification target that was processed */
    private java.lang.String recipientId;
    private java.time.Instant createdAt;
    /** Final processing status returned by notification-service */
    private com.document.notification.system.kafka.document.avro.model.NotificationStatus notificationStatus;
    /** Business or technical errors produced while sending the notification */
    private java.util.List<java.lang.String> failureMessages;
    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public NotificationResponseAvroModel() {
    }
    /**
     * All-args constructor.
     * @param id The new value for id
     * @param sagaId The new value for sagaId
     * @param notificationId The new value for notificationId
     * @param documentId The new value for documentId
     * @param recipientId Notification target that was processed
     * @param createdAt The new value for createdAt
     * @param notificationStatus Final processing status returned by notification-service
     * @param failureMessages Business or technical errors produced while sending the notification
     */
    public NotificationResponseAvroModel(java.lang.String id, java.lang.String sagaId, java.lang.String notificationId, java.lang.String documentId, java.lang.String recipientId, java.time.Instant createdAt, com.document.notification.system.kafka.document.avro.model.NotificationStatus notificationStatus, java.util.List<java.lang.String> failureMessages) {
        this.id = id;
        this.sagaId = sagaId;
        this.notificationId = notificationId;
        this.documentId = documentId;
        this.recipientId = recipientId;
        this.createdAt = createdAt.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
        this.notificationStatus = notificationStatus;
        this.failureMessages = failureMessages;
    }

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<NotificationResponseAvroModel> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<NotificationResponseAvroModel> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<NotificationResponseAvroModel> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<NotificationResponseAvroModel>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Deserializes a NotificationResponseAvroModel from a ByteBuffer.
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a NotificationResponseAvroModel instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static NotificationResponseAvroModel fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    /**
     * Creates a new NotificationResponseAvroModel RecordBuilder.
     * @return A new NotificationResponseAvroModel RecordBuilder
     */
    public static com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder newBuilder() {
        return new com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder();
    }

    /**
     * Creates a new NotificationResponseAvroModel RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new NotificationResponseAvroModel RecordBuilder
     */
    public static com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder newBuilder(com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder other) {
        if (other == null) {
            return new com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder();
        } else {
            return new com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder(other);
        }
    }

    /**
     * Creates a new NotificationResponseAvroModel RecordBuilder by copying an existing NotificationResponseAvroModel instance.
     * @param other The existing instance to copy.
     * @return A new NotificationResponseAvroModel RecordBuilder
     */
    public static com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder newBuilder(com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel other) {
        if (other == null) {
            return new com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder();
        } else {
            return new com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder(other);
        }
    }

    /**
     * Serializes this NotificationResponseAvroModel to a ByteBuffer.
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return id;
            case 1:
                return sagaId;
            case 2:
                return notificationId;
            case 3:
                return documentId;
            case 4:
                return recipientId;
            case 5:
                return createdAt;
            case 6:
                return notificationStatus;
            case 7:
                return failureMessages;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    @Override
    public org.apache.avro.Conversion<?> getConversion(int field) {
        return conversions[field];
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                id = value$ != null ? value$.toString() : null;
                break;
            case 1:
                sagaId = value$ != null ? value$.toString() : null;
                break;
            case 2:
                notificationId = value$ != null ? value$.toString() : null;
                break;
            case 3:
                documentId = value$ != null ? value$.toString() : null;
                break;
            case 4:
                recipientId = value$ != null ? value$.toString() : null;
                break;
            case 5:
                createdAt = (java.time.Instant) value$;
                break;
            case 6:
                notificationStatus = (com.document.notification.system.kafka.document.avro.model.NotificationStatus) value$;
                break;
            case 7:
                failureMessages = (java.util.List<java.lang.String>) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'id' field.
     * @return The value of the 'id' field.
     */
    public java.lang.String getId() {
        return id;
    }

    /**
     * Sets the value of the 'id' field.
     * @param value the value to set.
     */
    public void setId(java.lang.String value) {
        this.id = value;
    }

    /**
     * Gets the value of the 'sagaId' field.
     * @return The value of the 'sagaId' field.
     */
    public java.lang.String getSagaId() {
        return sagaId;
    }

    /**
     * Sets the value of the 'sagaId' field.
     * @param value the value to set.
     */
    public void setSagaId(java.lang.String value) {
        this.sagaId = value;
    }

    /**
     * Gets the value of the 'notificationId' field.
     * @return The value of the 'notificationId' field.
     */
    public java.lang.String getNotificationId() {
        return notificationId;
    }

    /**
     * Sets the value of the 'notificationId' field.
     * @param value the value to set.
     */
    public void setNotificationId(java.lang.String value) {
        this.notificationId = value;
    }

    /**
     * Gets the value of the 'documentId' field.
     * @return The value of the 'documentId' field.
     */
    public java.lang.String getDocumentId() {
        return documentId;
    }

    /**
     * Sets the value of the 'documentId' field.
     * @param value the value to set.
     */
    public void setDocumentId(java.lang.String value) {
        this.documentId = value;
    }

    /**
     * Gets the value of the 'recipientId' field.
     * @return Notification target that was processed
     */
    public java.lang.String getRecipientId() {
        return recipientId;
    }

    /**
     * Sets the value of the 'recipientId' field.
     * Notification target that was processed
     * @param value the value to set.
     */
    public void setRecipientId(java.lang.String value) {
        this.recipientId = value;
    }

    /**
     * Gets the value of the 'createdAt' field.
     * @return The value of the 'createdAt' field.
     */
    public java.time.Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the value of the 'createdAt' field.
     * @param value the value to set.
     */
    public void setCreatedAt(java.time.Instant value) {
        this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    }

    /**
     * Gets the value of the 'notificationStatus' field.
     * @return Final processing status returned by notification-service
     */
    public com.document.notification.system.kafka.document.avro.model.NotificationStatus getNotificationStatus() {
        return notificationStatus;
    }

    /**
     * Sets the value of the 'notificationStatus' field.
     * Final processing status returned by notification-service
     * @param value the value to set.
     */
    public void setNotificationStatus(com.document.notification.system.kafka.document.avro.model.NotificationStatus value) {
        this.notificationStatus = value;
    }

    /**
     * Gets the value of the 'failureMessages' field.
     * @return Business or technical errors produced while sending the notification
     */
    public java.util.List<java.lang.String> getFailureMessages() {
        return failureMessages;
    }

    /**
     * Sets the value of the 'failureMessages' field.
     * Business or technical errors produced while sending the notification
     * @param value the value to set.
     */
    public void setFailureMessages(java.util.List<java.lang.String> value) {
        this.failureMessages = value;
    }

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    /**
     * RecordBuilder for NotificationResponseAvroModel instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<NotificationResponseAvroModel>
            implements org.apache.avro.data.RecordBuilder<NotificationResponseAvroModel> {

        private java.lang.String id;
        private java.lang.String sagaId;
        private java.lang.String notificationId;
        private java.lang.String documentId;
        /** Notification target that was processed */
        private java.lang.String recipientId;
        private java.time.Instant createdAt;
        /** Final processing status returned by notification-service */
        private com.document.notification.system.kafka.document.avro.model.NotificationStatus notificationStatus;
        /** Business or technical errors produced while sending the notification */
        private java.util.List<java.lang.String> failureMessages;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.id)) {
                this.id = data().deepCopy(fields()[0].schema(), other.id);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.sagaId)) {
                this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
            if (isValidValue(fields()[2], other.notificationId)) {
                this.notificationId = data().deepCopy(fields()[2].schema(), other.notificationId);
                fieldSetFlags()[2] = other.fieldSetFlags()[2];
            }
            if (isValidValue(fields()[3], other.documentId)) {
                this.documentId = data().deepCopy(fields()[3].schema(), other.documentId);
                fieldSetFlags()[3] = other.fieldSetFlags()[3];
            }
            if (isValidValue(fields()[4], other.recipientId)) {
                this.recipientId = data().deepCopy(fields()[4].schema(), other.recipientId);
                fieldSetFlags()[4] = other.fieldSetFlags()[4];
            }
            if (isValidValue(fields()[5], other.createdAt)) {
                this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
                fieldSetFlags()[5] = other.fieldSetFlags()[5];
            }
            if (isValidValue(fields()[6], other.notificationStatus)) {
                this.notificationStatus = data().deepCopy(fields()[6].schema(), other.notificationStatus);
                fieldSetFlags()[6] = other.fieldSetFlags()[6];
            }
            if (isValidValue(fields()[7], other.failureMessages)) {
                this.failureMessages = data().deepCopy(fields()[7].schema(), other.failureMessages);
                fieldSetFlags()[7] = other.fieldSetFlags()[7];
            }
        }

        /**
         * Creates a Builder by copying an existing NotificationResponseAvroModel instance
         * @param other The existing instance to copy.
         */
        private Builder(com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.id)) {
                this.id = data().deepCopy(fields()[0].schema(), other.id);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.sagaId)) {
                this.sagaId = data().deepCopy(fields()[1].schema(), other.sagaId);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.notificationId)) {
                this.notificationId = data().deepCopy(fields()[2].schema(), other.notificationId);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.documentId)) {
                this.documentId = data().deepCopy(fields()[3].schema(), other.documentId);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.recipientId)) {
                this.recipientId = data().deepCopy(fields()[4].schema(), other.recipientId);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.createdAt)) {
                this.createdAt = data().deepCopy(fields()[5].schema(), other.createdAt);
                fieldSetFlags()[5] = true;
            }
            if (isValidValue(fields()[6], other.notificationStatus)) {
                this.notificationStatus = data().deepCopy(fields()[6].schema(), other.notificationStatus);
                fieldSetFlags()[6] = true;
            }
            if (isValidValue(fields()[7], other.failureMessages)) {
                this.failureMessages = data().deepCopy(fields()[7].schema(), other.failureMessages);
                fieldSetFlags()[7] = true;
            }
        }

        /**
         * Gets the value of the 'id' field.
         * @return The value.
         */
        public java.lang.String getId() {
            return id;
        }


        /**
         * Sets the value of the 'id' field.
         * @param value The value of 'id'.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder setId(java.lang.String value) {
            validate(fields()[0], value);
            this.id = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'id' field has been set.
         * @return True if the 'id' field has been set, false otherwise.
         */
        public boolean hasId() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'id' field.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder clearId() {
            id = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'sagaId' field.
         * @return The value.
         */
        public java.lang.String getSagaId() {
            return sagaId;
        }


        /**
         * Sets the value of the 'sagaId' field.
         * @param value The value of 'sagaId'.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder setSagaId(java.lang.String value) {
            validate(fields()[1], value);
            this.sagaId = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'sagaId' field has been set.
         * @return True if the 'sagaId' field has been set, false otherwise.
         */
        public boolean hasSagaId() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'sagaId' field.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder clearSagaId() {
            sagaId = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'notificationId' field.
         * @return The value.
         */
        public java.lang.String getNotificationId() {
            return notificationId;
        }


        /**
         * Sets the value of the 'notificationId' field.
         * @param value The value of 'notificationId'.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder setNotificationId(java.lang.String value) {
            validate(fields()[2], value);
            this.notificationId = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'notificationId' field has been set.
         * @return True if the 'notificationId' field has been set, false otherwise.
         */
        public boolean hasNotificationId() {
            return fieldSetFlags()[2];
        }


        /**
         * Clears the value of the 'notificationId' field.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder clearNotificationId() {
            notificationId = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        /**
         * Gets the value of the 'documentId' field.
         * @return The value.
         */
        public java.lang.String getDocumentId() {
            return documentId;
        }


        /**
         * Sets the value of the 'documentId' field.
         * @param value The value of 'documentId'.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder setDocumentId(java.lang.String value) {
            validate(fields()[3], value);
            this.documentId = value;
            fieldSetFlags()[3] = true;
            return this;
        }

        /**
         * Checks whether the 'documentId' field has been set.
         * @return True if the 'documentId' field has been set, false otherwise.
         */
        public boolean hasDocumentId() {
            return fieldSetFlags()[3];
        }


        /**
         * Clears the value of the 'documentId' field.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder clearDocumentId() {
            documentId = null;
            fieldSetFlags()[3] = false;
            return this;
        }

        /**
         * Gets the value of the 'recipientId' field.
         * Notification target that was processed
         * @return The value.
         */
        public java.lang.String getRecipientId() {
            return recipientId;
        }


        /**
         * Sets the value of the 'recipientId' field.
         * Notification target that was processed
         * @param value The value of 'recipientId'.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder setRecipientId(java.lang.String value) {
            validate(fields()[4], value);
            this.recipientId = value;
            fieldSetFlags()[4] = true;
            return this;
        }

        /**
         * Checks whether the 'recipientId' field has been set.
         * Notification target that was processed
         * @return True if the 'recipientId' field has been set, false otherwise.
         */
        public boolean hasRecipientId() {
            return fieldSetFlags()[4];
        }


        /**
         * Clears the value of the 'recipientId' field.
         * Notification target that was processed
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder clearRecipientId() {
            recipientId = null;
            fieldSetFlags()[4] = false;
            return this;
        }

        /**
         * Gets the value of the 'createdAt' field.
         * @return The value.
         */
        public java.time.Instant getCreatedAt() {
            return createdAt;
        }


        /**
         * Sets the value of the 'createdAt' field.
         * @param value The value of 'createdAt'.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder setCreatedAt(java.time.Instant value) {
            validate(fields()[5], value);
            this.createdAt = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
            fieldSetFlags()[5] = true;
            return this;
        }

        /**
         * Checks whether the 'createdAt' field has been set.
         * @return True if the 'createdAt' field has been set, false otherwise.
         */
        public boolean hasCreatedAt() {
            return fieldSetFlags()[5];
        }


        /**
         * Clears the value of the 'createdAt' field.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder clearCreatedAt() {
            fieldSetFlags()[5] = false;
            return this;
        }

        /**
         * Gets the value of the 'notificationStatus' field.
         * Final processing status returned by notification-service
         * @return The value.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationStatus getNotificationStatus() {
            return notificationStatus;
        }


        /**
         * Sets the value of the 'notificationStatus' field.
         * Final processing status returned by notification-service
         * @param value The value of 'notificationStatus'.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder setNotificationStatus(com.document.notification.system.kafka.document.avro.model.NotificationStatus value) {
            validate(fields()[6], value);
            this.notificationStatus = value;
            fieldSetFlags()[6] = true;
            return this;
        }

        /**
         * Checks whether the 'notificationStatus' field has been set.
         * Final processing status returned by notification-service
         * @return True if the 'notificationStatus' field has been set, false otherwise.
         */
        public boolean hasNotificationStatus() {
            return fieldSetFlags()[6];
        }


        /**
         * Clears the value of the 'notificationStatus' field.
         * Final processing status returned by notification-service
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder clearNotificationStatus() {
            notificationStatus = null;
            fieldSetFlags()[6] = false;
            return this;
        }

        /**
         * Gets the value of the 'failureMessages' field.
         * Business or technical errors produced while sending the notification
         * @return The value.
         */
        public java.util.List<java.lang.String> getFailureMessages() {
            return failureMessages;
        }


        /**
         * Sets the value of the 'failureMessages' field.
         * Business or technical errors produced while sending the notification
         * @param value The value of 'failureMessages'.
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder setFailureMessages(java.util.List<java.lang.String> value) {
            validate(fields()[7], value);
            this.failureMessages = value;
            fieldSetFlags()[7] = true;
            return this;
        }

        /**
         * Checks whether the 'failureMessages' field has been set.
         * Business or technical errors produced while sending the notification
         * @return True if the 'failureMessages' field has been set, false otherwise.
         */
        public boolean hasFailureMessages() {
            return fieldSetFlags()[7];
        }


        /**
         * Clears the value of the 'failureMessages' field.
         * Business or technical errors produced while sending the notification
         * @return This builder.
         */
        public com.document.notification.system.kafka.document.avro.model.NotificationResponseAvroModel.Builder clearFailureMessages() {
            failureMessages = null;
            fieldSetFlags()[7] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public NotificationResponseAvroModel build() {
            try {
                NotificationResponseAvroModel record = new NotificationResponseAvroModel();
                record.id = fieldSetFlags()[0] ? this.id : (java.lang.String) defaultValue(fields()[0]);
                record.sagaId = fieldSetFlags()[1] ? this.sagaId : (java.lang.String) defaultValue(fields()[1]);
                record.notificationId = fieldSetFlags()[2] ? this.notificationId : (java.lang.String) defaultValue(fields()[2]);
                record.documentId = fieldSetFlags()[3] ? this.documentId : (java.lang.String) defaultValue(fields()[3]);
                record.recipientId = fieldSetFlags()[4] ? this.recipientId : (java.lang.String) defaultValue(fields()[4]);
                record.createdAt = fieldSetFlags()[5] ? this.createdAt : (java.time.Instant) defaultValue(fields()[5]);
                record.notificationStatus = fieldSetFlags()[6] ? this.notificationStatus : (com.document.notification.system.kafka.document.avro.model.NotificationStatus) defaultValue(fields()[6]);
                record.failureMessages = fieldSetFlags()[7] ? this.failureMessages : (java.util.List<java.lang.String>) defaultValue(fields()[7]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

}










