/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package com.document.notification.system.kafka.document.avro.model;

@org.apache.avro.specific.AvroGenerated
public enum NotificationStatus implements org.apache.avro.generic.GenericEnumSymbol<NotificationStatus> {
    NOTIFICATION_PENDING, NOTIFICATION_SENT, NOTIFICATION_CANCELLED, NOTIFICATION_FAILED;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"NotificationStatus\",\"namespace\":\"com.document.notification.system.kafka.document.avro.model\",\"symbols\":[\"NOTIFICATION_PENDING\",\"NOTIFICATION_SENT\",\"NOTIFICATION_CANCELLED\",\"NOTIFICATION_FAILED\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
