server:
  port: ${SERVER_PORT:8183}

logging:
  level:
    com.document.notification.system: DEBUG


notification-service:
  instance-id: ${NOTIFICATION_INSTANCE_ID:notification-1}
  notification-request-topic-name: notification-request
  notification-response-topic-name: notification-response
  outbox-scheduler-fixed-rate: 10000
  outbox-scheduler-initial-delay: 10000
  mail:
    from: ${MAIL_FROM:no-reply@example.com}
    rate-limit:
      tokens-per-interval: ${MAIL_RATE_LIMIT_TOKENS:5}
      refill-interval-ms: ${MAIL_RATE_LIMIT_REFILL_MS:20000}

spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5434/postgres?currentSchema=notification&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    platform: postgres
  sql:
    init:
      ##schema-locations: classpath:init-schema.sql
      mode: ${SQL_INIT_MODE:always}
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:no-reply@example.com}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS_ENABLE:true}
            required: ${MAIL_SMTP_STARTTLS_REQUIRED:true}
          connectiontimeout: ${MAIL_SMTP_CONNECTION_TIMEOUT:5000}
          timeout: ${MAIL_SMTP_TIMEOUT:5000}
          writetimeout: ${MAIL_SMTP_WRITE_TIMEOUT:5000}
        transport:
          protocol: smtp

kafka-config:
  bootstrap-servers: localhost:19092, localhost:29092, localhost:39092
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  num-of-partitions: 3
  replication-factor: 3

kafka-producer-config:
  key-serializer-class: org.apache.kafka.common.serialization.StringSerializer
  value-serializer-class: io.confluent.kafka.serializers.KafkaAvroSerializer
  compression-type: snappy
  acks: all
  batch-size: 16384
  batch-size-boost-factor: 100
  linger-ms: 5
  request-timeout-ms: 60000
  retry-count: 5

kafka-consumer-config:
  key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
  notification-consumer-group-id: notification-topic-consumer
  auto-offset-reset: earliest
  specific-avro-reader-key: specific.avro.reader
  specific-avro-reader: true
  batch-listener: true
  auto-startup: true
  concurrency-level: 3
  session-timeout-ms: 10000
  heartbeat-interval-ms: 3000
  max-poll-interval-ms: 300000
  max-poll-records: 100
  max-partition-fetch-bytes-default: 1048576
  max-partition-fetch-bytes-boost-factor: 1
  poll-timeout-ms: 150
